{
 "title": "Grafana Test",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Utilisation RAM (%)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux de Succès des Tests (sur les 50 dernières minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(\n  rate(playwright_tests_succeeded_total[50m])\n/\n  (rate(playwright_tests_succeeded_total[50m]) + rate(playwright_tests_failed_total[50m]) + 1e-9)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "interruptions Système par seconde",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "interrupts/sec" } },
   "targets": [
    { "expr": "rate(node_intr_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tests ratés",
   "type": "stat",
   "description": "playwright_tests_failed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "playwright_tests_failed_total\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Données Prometheus récupère à chaque balayage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "scrape_samples_scraped\n", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "Statut des Cibles Prometheus : Metrics.js",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"playwright-metrics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tests réusssis",
   "type": "stat",
   "description": "playwright_tests_succeeded_total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "playwright_tests_succeeded_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utlisation CPU",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statut des Cibles Prometheus : docker  node_exporter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution de la Durée des Tests",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(playwright_test_duration_seconds_bucket[5m])) by (le)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durée pour récuperer les données des Cibles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "Durée Moyenne d'Exécution des Tests (sur les 30 dernières minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(playwright_test_duration_seconds_sum[30m])\n/\n(rate(playwright_test_duration_seconds_count[30m]) + 1e-9)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation Disque ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{device=\"dm-0\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durée d'Exécution P95 (Percentile 95)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(playwright_test_duration_seconds_bucket[5m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}